/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id integer NOT NULL,
    name varchar(100) NOT NULL,
    date_of_birth date NOT NULL,
    escape_attempts integer NOT NULL,
    neutered boolean NOT NULL,
    weight_kg decimal(5,2) NOT NULL,
);

ALTER TABLE animals
ADD species varchar(100);

CREATE TABLE owners (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	full_name varchar(100),
	age integer
);
SELECT * from owners;

CREATE TABLE species (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100)
);
SELECT * from species;

-- Make sure that id is set as autoincremented PRIMARY KEY
ALTER TABLE animals
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE animals
ADD PRIMARY KEY (id);
SELECT * from animals;

-- Remove column species
BEGIN;
ALTER TABLE animals
DROP COLUMN species;
COMMIT;
SELECT * from animals;

-- Add column species_id which is a foreign key referencing species table
BEGIN;
ALTER TABLE animals
ADD species_id integer;
COMMIT;

ALTER TABLE species
ADD PRIMARY KEY (id);

BEGIN;
ALTER TABLE animals
ADD CONSTRAINT fk_species
FOREIGN KEY(species_id)
REFERENCES species(id)
ON DELETE CASCADE;
COMMIT;
SELECT * from animals;

-- Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE owners
ADD PRIMARY KEY (id);
SELECT * from owners;

BEGIN;
ALTER TABLE animals
ADD owner_id integer;
COMMIT;

BEGIN;
ALTER TABLE animals
ADD CONSTRAINT fk_owners
FOREIGN KEY(owner_id)
REFERENCES owners(id)
ON DELETE CASCADE;
COMMIT;
SELECT * from animals;