-- Create database clinic
CREATE DATABASE clinic;

-- Create Patients table
CREATE TABLE patients  (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(30),
  date_of_birth DATE,
  PRIMARY KEY(id)
);

-- Create Medical histories table
CREATE TABLE medical_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP,
  patients_id INT,
  FOREIGN KEY(patients_id) REFERENCES patients(id),
  status VARCHAR(100),
  PRIMARY KEY(id)
);

-- Create table treatments
CREATE TABLE treatments (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(100),
  name VARCHAR(100),
  PRIMARY KEY (id)
);

-- Create table invoices
CREATE TABLE invoices (
id INT GENERATED BY DEFAULT AS IDENTITY,
total_amount DECIMAL,
generated_at TIMESTAMP,
payed_at TIMESTAMP,
medical_history_id INT,
FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id),
PRIMARY KEY (id)
);

-- Create table invoice_items
CREATE TABLE invoice_items (
id INT GENERATED BY DEFAULT AS IDENTITY,
unit_price DECIMAL,
quantity INT,
total_price DECIMAL,
invoice_id INT,
treatment_id INT,
FOREIGN KEY (invoice_id) REFERENCES invoices(id),
FOREIGN KEY (treatment_id) REFERENCES treatments(id),
PRIMARY KEY (id)
);

-- Create table history_treatments_link 
CREATE TABLE history_treatments_link (
medical_history_id INT,
treatments_id INT,
FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id),
FOREIGN KEY (treatments_id) REFERENCES treatments (id)
);

CREATE INDEX patients_asc ON medical_histories(patients_id asc) INCLUDE (id, admitted_at);
CREATE INDEX medical_histories_asc ON invoices(medical_history_id asc) INCLUDE (id, generated_at, payed_at);
CREATE INDEX invoices_asc ON invoice_items(invoice_id asc) INCLUDE (id, unit_price, quantity);
CREATE INDEX treatments_asc ON invoice_items(treatment_id asc) INCLUDE (id, unit_price, quantity);
CREATE INDEX medical_history_id_asc ON history_treatments_link (medical_history_id asc);
