/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id integer NOT NULL,
    name varchar(100) NOT NULL,
    date_of_birth date NOT NULL,
    escape_attempts integer NOT NULL,
    neutered boolean NOT NULL,
    weight_kg decimal(5,2) NOT NULL,
);

ALTER TABLE animals
ADD species varchar(100);

CREATE TABLE owners (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	full_name varchar(100),
	age integer
);
SELECT * from owners;

CREATE TABLE species (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100)
);
SELECT * from species;

-- Make sure that id is set as autoincremented PRIMARY KEY
ALTER TABLE animals
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE animals
ADD PRIMARY KEY (id);
SELECT * from animals;

-- Remove column species
BEGIN;
ALTER TABLE animals
DROP COLUMN species;
COMMIT;
SELECT * from animals;

-- Add column species_id which is a foreign key referencing species table
BEGIN;
ALTER TABLE animals
ADD species_id integer;
COMMIT;

ALTER TABLE species
ADD PRIMARY KEY (id);

BEGIN;
ALTER TABLE animals
ADD CONSTRAINT fk_species
FOREIGN KEY(species_id)
REFERENCES species(id)
ON DELETE CASCADE;
COMMIT;
SELECT * from animals;

-- Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE owners
ADD PRIMARY KEY (id);
SELECT * from owners;

BEGIN;
ALTER TABLE animals
ADD owner_id integer;
COMMIT;

BEGIN;
ALTER TABLE animals
ADD CONSTRAINT fk_owners
FOREIGN KEY(owner_id)
REFERENCES owners(id)
ON DELETE CASCADE;
COMMIT;
SELECT * from animals;


-- Create a table named vets
CREATE TABLE vets (
id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name varchar(100),
age integer,
date_of_graduation date,
PRIMARY KEY (id)
);

-- Create a "join table" called specializations
CREATE TABLE specializations (
spec_id integer,
vet_id integer,
CONSTRAINT fk_vets FOREIGN KEY (vet_id) REFERENCES vets(id),
CONSTRAINT fk_species FOREIGN KEY (spec_id) REFERENCES species(id)
);
SELECT * FROM specializations

-- Create a "join table" called visits
CREATE TABLE visits (
animal_id integer,
vet_id integer,
date_of_visit date,
CONSTRAINT fk_animals FOREIGN KEY (animal_id) REFERENCES animals(id),
CONSTRAINT fk_vets FOREIGN KEY (vet_id) REFERENCES vets(id)
);
SELECT * FROM visits

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

-- Create index to optimize queries
create index id_btree on visits using btree(animal_id) where animal_id = 4;

create index vets_asc1 on visits(vet_id asc) include (animal_id, date_of_visit);

create index owners_asc1 on owners(email desc) include (id, full_name, age);


-- Add email column to owners table
ALTER TABLE animals ADD COLUMN email VARCHAR(120);

-- Create indexes to optimize queries
CREATE INDEX id_btree ON visits USING btree(animal_id) WHERE animal_id = 4;

CREATE INDEX vets_asc ON visits(vet_id asc) INCLUDE (animal_id, date_of_visit);

CREATE INDEX owners_asc ON owners(email desc) INCLUDE (id, full_name, age);